[env]
LIB = "web"
PROFILE = "release"
OUT_DIR = "app/${LIB}/static/wasm"

[tasks.run-web]
command = "deno"
cwd = "./app/${LIB}"
args = ["task", "start"]
workspace = false

[tasks.build-rust-web]
command = "cargo"
args = [
    "build",
    "-p",
    "*_app_${LIB}",
    "--target",
    "wasm32-unknown-unknown",
    "--profile",
    "${PROFILE}",
]
workspace = false

[tasks.bindgen-web]
command = "wasm-bindgen"
args = [
    "--target",
    "deno",
    "--no-typescript",
    "target/wasm32-unknown-unknown/${PROFILE}/chess_app_${LIB}.wasm",
    "--out-dir",
    "${OUT_DIR}",
    "--out-name",
    "chess_web",
]
dependencies = ["build-rust-web"]
workspace = false

[tasks.build-web]
command = "wasm-opt"
args = [
    "-Oz",
    "-o",
    "${OUT_DIR}/chess_${LIB}_bg.wasm",
    "${OUT_DIR}/chess_${LIB}_bg.wasm",
]
dependencies = ["bindgen-web"]
workspace = false
