[env]
LIB = "web"
PROFILE = "release"
APP_DIR = "app/${LIB}"

[tasks.run-server]
command = "cargo"
args = ["run", "-p", "chess_app_server", "--profile", "${PROFILE}"]
workspace = false

[tasks.build-web]
cwd = "./${APP_DIR}"
command = "wasm-pack"
args = [
    "build",
    "--target",
    "no-modules",
    "--release",
    "--out-dir",
    "static/wasm",
]
workspace = false

[tasks.run-web]
command = "deno"
cwd = "./${APP_DIR}"
args = ["task", "start"]
workspace = false
