[package]
name = "chess_app_server"
version = "0.1.0"
authors = ["Sean Sullivan <me@snen.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
wildchess = { workspace = true }

bevy = { workspace = true }
