[package]
name = "classical_board"
version = "0.1.0"
edition = "2021"

[dependencies]
chess = { path = "../../chess" }
bevy = { version = "0.11" }
rand = { version = "0.8.5 " }
itertools = { version = "0.11" }
