[package]
name = "chess_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
games = { path = "../games" }
layouts = { path = "../layouts" }
bevy = { version = "0.11" }
bevy_egui = { version = "0.21" }
egui_extras = { version = "0.22", features = ["svg"] }
itertools = "*"

[dev-dependencies]
bevy_geppetto = { git = "https://github.com/snendev/bevy_geppetto.git" }
